import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import * as cheerio from "npm:cheerio@1.0.0";
type Job={id:string;request_url:string;city:string|null;state:string|null};type Item={business_name:string;city:string;state:string;postal_code:string;address:string;source_category:string;source_subcategory:string;detail_url:string;website_url:string;instagram_handle:string;public_email:string;public_phone:string;description:string;source_key:string};
const clean=(v:string)=>String(v||'').replace(/\u200b/g,'').replace(/\s+/g,' ').trim();const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});const abs=(href:string,base:string)=>{try{return new URL(href,base).toString()}catch{return''}};
function profileUrls(html:string,base:string){const $=cheerio.load(html),out:string[]=[];const seen=new Set<string>();$('a[href*="/business/"]').each((_i,a)=>{const url=abs($(a).attr('href')||'',base);if(!url||seen.has(url)||!/savorblk\.com\/business\//i.test(url))return;seen.add(url);out.push(url)});return out.slice(0,25)}
function externalSite($:cheerio.CheerioAPI,base:string){let found='';$('a[href]').each((_i,a)=>{if(found)return;const label=clean($(a).text()).toLowerCase(),href=abs($(a).attr('href')||'',base);if(!href||/instagram\.com|facebook\.com|tiktok\.com|youtube\.com|mailto:|tel:/i.test(href))return;try{const u=new URL(href);if(u.hostname.replace(/^www\./,'')==='savorblk.com')return;if(/website|visit|order online|official site/.test(label)||(/^https?:/.test(href)&&!u.hostname.includes('google.')))found=href}catch{}});return found}
function social($:cheerio.CheerioAPI,host:string){const href=$(`a[href*="${host}"]`).first().attr('href')||'';try{const u=new URL(href);return u.pathname.split('/').filter(Boolean)[0]||''}catch{return''}}
function addressFrom(text:string){const m=text.match(/\b\d{1,6}\s+[^\n|]{2,120}?,\s*[A-Za-z .'-]+,\s*[A-Z]{2}\s+\d{5}(?:-\d{4})?\b/);if(!m)return{address:'',city:'',state:'',postal_code:''};const address=clean(m[0]),loc=address.match(/,\s*([^,]+),\s*([A-Z]{2})\s+(\d{5}(?:-\d{4})?)$/i);return{address,city:clean(loc?.[1]||''),state:(loc?.[2]||'').toUpperCase(),postal_code:loc?.[3]||''}}
function phone(text:string){return clean(text).replace(/\b\d{5}(?:-\d{4})?\b/g,' ').match(/(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}/)?.[0]||''}
function typeFrom(title:string,text:string){const t=`${title} ${text.slice(0,600)}`.toLowerCase();if(/black-owned\s+coffee|coffee shop/.test(t))return'Coffee Shop';if(/food truck/.test(t))return'Food Truck';if(/cater|private chef|chef services/.test(t))return'Catering';if(/dessert|sweet shop|bakery|confection/.test(t))return'Bakery & Dessert';if(/black-owned\s+bar|\bbar\b/.test(t))return'Bar';if(/black-owned\s+lounge|\blounge\b/.test(t))return'Lounge';if(/restaurant|black-owned\s+food/.test(t))return'Restaurant';return''}
async function detail(url:string,job:Job):Promise<Item|null>{const r=await fetch(url,{headers:{'User-Agent':'TheBlackPagesSavorBLK/1.0 (+public Black-owned business directory indexing)','Accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(15000)});if(!r.ok)return null;const html=await r.text(),$=cheerio.load(html),title=clean($('title').text()),body=clean($('body').text()),name=clean($('h1').first().text())||clean(title.split('—')[0]);if(!name||name.length>220)return null;const kind=typeFrom(title,body);if(!kind)return null;if(/events? brand|event series|promoter|day party/i.test(`${title} ${body.slice(0,1200)}`)&&!/restaurant|bar|lounge|coffee|catering|bakery|food truck/i.test(kind))return null;const loc=addressFrom(body),city=loc.city||job.city||'',state=loc.state||job.state||'',description=clean($('meta[name="description"]').attr('content')||$('main p').first().text()||$('p').first().text()).slice(0,1000);const website=externalSite($,url);const item:Item={business_name:name,city,state,postal_code:loc.postal_code,address:loc.address,source_category:kind==='Bar'||kind==='Lounge'?'Nightlife':'Food & Beverage',source_subcategory:kind,detail_url:url,website_url:website,instagram_handle:social($,'instagram.com'),public_email:($('a[href^="mailto:"]').first().attr('href')||'').replace(/^mailto:/i,'').split('?')[0],public_phone:phone(body),description,source_key:url.slice(0,180)};return item}
async function process(supabase:ReturnType<typeof createClient>,job:Job){try{const r=await fetch(job.request_url,{headers:{'User-Agent':'TheBlackPagesSavorBLK/1.0 (+public Black-owned business directory indexing)','Accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(18000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const urls=profileUrls(await r.text(),job.request_url);const settled=await Promise.allSettled(urls.map(u=>detail(u,job)));const items=settled.filter((x):x is PromiseFulfilledResult<Item|null>=>x.status==='fulfilled'&&x.value!==null).map(x=>x.value as Item);const {data,error}=await supabase.rpc('black_pages_complete_external_job_fast',{p_job_id:job.id,p_items:items,p_error:null});if(error)throw new Error(error.message);return{job_id:job.id,found:items.length,profiles:urls.length,result:data}}catch(e){const message=e instanceof Error?e.message:String(e);await supabase.rpc('black_pages_complete_external_job_fast',{p_job_id:job.id,p_items:[],p_error:message});return{job_id:job.id,error:message}}}
Deno.serve(async request=>{if(request.method!=='POST')return json({error:'Method not allowed'},405);const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)return json({error:'Worker environment incomplete'},500);const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),token=request.headers.get('x-worker-token')||'';const {data:ok}=await supabase.rpc('black_pages_authorize_worker_token',{p_token:token});if(ok!==true)return json({error:'Unauthorized'},401);let body:{jobs?:number}={};try{body=await request.json()}catch{}const {data:claim,error}=await supabase.rpc('black_pages_claim_savorblk_jobs',{p_limit:Math.min(6,Math.max(1,Number(body.jobs)||2))});if(error)return json({error:error.message},500);const jobs=Array.isArray(claim?.jobs)?claim.jobs as Job[]:[];const settled=await Promise.allSettled(jobs.map(j=>process(supabase,j)));await supabase.rpc('black_pages_auto_classify_batch',{p_limit:30000});await supabase.rpc('black_pages_context_classify_batch',{p_limit:30000});await supabase.rpc('black_pages_preverify_batch',{p_limit:30000});await supabase.rpc('black_pages_resolve_candidate_identities',{p_limit:50000});return json({ok:true,claimed:jobs.length,processed:settled.length,outcomes:settled.map(x=>x.status==='fulfilled'?x.value:{error:String(x.reason)})})});