import type { SupabaseClient } from '@supabase/supabase-js'
import type { Database, Json } from '../lib/database.types.ts'

export type IdentityReviewTier='ready'|'research'|'hold'
export type IdentityEvidence={candidate_id:string;source_key:string;source_name:string;ownership_signal:string;source_url:string;website_url:string;phone:string;email:string;address:string;verification_score:number;verification_tier:string;pipeline_stage:string}
export type IdentityReviewBusiness={
  identity_id:string;business_name:string;city:string;state:string;category:string;subcategory:string;member_count:number;source_count:number;identity_confidence:number;status:string;max_verification_score:number;ready_members:number;research_members:number;hold_members:number;approved_members:number;pending_members:number;source_keys:string[];source_names:string[];evidence_urls:string[];certified_black_source:boolean;strong_directory_source:boolean;review_tier:IdentityReviewTier;website_url:string;instagram_handle:string;public_email:string;public_phone:string;source_address:string;external_source_url:string;evidence:IdentityEvidence[]
}
export type IdentityReviewSnapshot={counts:{ready:number;research:number;hold:number;multi_source:number;duplicate_rows_collapsed:number};identities:IdentityReviewBusiness[];generated_at:string}

type TypedClient=SupabaseClient<Database>
type RpcResult={data:Json|null;error:{message:string}|null}
const numberValue=(value:unknown)=>{const n=Number(value);return Number.isFinite(n)?n:0}
const recordValue=(value:unknown):Record<string,unknown>=>Boolean(value)&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:{}
const records=(value:unknown):Record<string,unknown>[]=>Array.isArray(value)?value.filter((item):item is Record<string,unknown>=>Boolean(item)&&typeof item==='object'&&!Array.isArray(item)):[]
const strings=(value:unknown):string[]=>Array.isArray(value)?value.map(String).filter(Boolean):[]
const bool=(value:unknown)=>value===true||value==='true'
const tier=(value:unknown):IdentityReviewTier=>value==='ready'||value==='research'?value:'hold'
function rpcClient(supabase:TypedClient){return supabase.rpc.bind(supabase) as unknown as(fn:string,args:Record<string,unknown>)=>Promise<RpcResult>}
function parseEvidence(value:unknown):IdentityEvidence[]{return records(value).map(item=>({candidate_id:String(item.candidate_id||''),source_key:String(item.source_key||''),source_name:String(item.source_name||''),ownership_signal:String(item.ownership_signal||''),source_url:String(item.source_url||''),website_url:String(item.website_url||''),phone:String(item.phone||''),email:String(item.email||''),address:String(item.address||''),verification_score:numberValue(item.verification_score),verification_tier:String(item.verification_tier||''),pipeline_stage:String(item.pipeline_stage||'')}))}
function parseSnapshot(value:Json):IdentityReviewSnapshot{const root=recordValue(value),counts=recordValue(root.counts);return{counts:{ready:numberValue(counts.ready),research:numberValue(counts.research),hold:numberValue(counts.hold),multi_source:numberValue(counts.multi_source),duplicate_rows_collapsed:numberValue(counts.duplicate_rows_collapsed)},identities:records(root.identities).map(item=>({identity_id:String(item.identity_id||''),business_name:String(item.business_name||''),city:String(item.city||''),state:String(item.state||''),category:String(item.category||''),subcategory:String(item.subcategory||''),member_count:numberValue(item.member_count),source_count:numberValue(item.source_count),identity_confidence:numberValue(item.identity_confidence),status:String(item.status||''),max_verification_score:numberValue(item.max_verification_score),ready_members:numberValue(item.ready_members),research_members:numberValue(item.research_members),hold_members:numberValue(item.hold_members),approved_members:numberValue(item.approved_members),pending_members:numberValue(item.pending_members),source_keys:strings(item.source_keys),source_names:strings(item.source_names),evidence_urls:strings(item.evidence_urls),certified_black_source:bool(item.certified_black_source),strong_directory_source:bool(item.strong_directory_source),review_tier:tier(item.review_tier),website_url:String(item.website_url||''),instagram_handle:String(item.instagram_handle||''),public_email:String(item.public_email||''),public_phone:String(item.public_phone||''),source_address:String(item.source_address||''),external_source_url:String(item.external_source_url||''),evidence:parseEvidence(item.evidence)})),generated_at:String(root.generated_at||'')}}

export async function fetchIdentityReviewSnapshot(supabase:TypedClient,city?:string|null,limit=1000){const{data,error}=await rpcClient(supabase)('black_pages_staff_identity_review_snapshot',{p_city:city||null,p_limit:limit});if(error||data==null)return{snapshot:null,error:error?.message||'Business identity review queue is unavailable.'};return{snapshot:parseSnapshot(data),error:''}}
export async function submitIdentityBatchReview(supabase:TypedClient,input:{identityIds:string[];decision:'approve'|'reject'|'needs_more_evidence';reason:string}){const{data,error}=await rpcClient(supabase)('black_pages_staff_batch_identity_review',{p_identity_ids:input.identityIds,p_decision:input.decision,p_reason:input.reason});if(error||data==null)return{result:null,error:error?.message||'Business identity review could not be saved.'};return{result:recordValue(data),error:''}}
