import type { SupabaseClient } from '@supabase/supabase-js'
import type { Database, Json } from '../lib/database.types.ts'
type Client=SupabaseClient<Database>;type RpcResult={data:Json|null;error:{message:string}|null}
const rec=(v:unknown):Record<string,unknown>=>Boolean(v)&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{}
const arr=(v:unknown):Record<string,unknown>[]=>Array.isArray(v)?v.filter((x):x is Record<string,unknown>=>Boolean(x)&&typeof x==='object'&&!Array.isArray(x)):[]
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0
const rpc=(s:Client)=>s.rpc.bind(s) as unknown as (fn:string,args:Record<string,unknown>)=>Promise<RpcResult>
export type SourcePerformance={source_key:string;source_name:string;adapter:string;ownership_signal:string;active:boolean;priority:number;candidate_records:number;unique_businesses:number;duplicate_records_merged:number;cities_covered:number;approved_businesses:number;published_businesses:number;verification_conversion_pct:number;jobs:number;successful_jobs:number;failed_jobs:number;inserted_across_jobs:number;bad_job_rate_pct:number;last_successful_crawl:string}
export type SourcePerformanceSnapshot={sources:SourcePerformance[];totals:{active_sources:number;candidate_records:number;business_identities:number;publication_ready:number;published_from_factory:number};generated_at:string}
function parse(v:Json):SourcePerformanceSnapshot{const r=rec(v),t=rec(r.totals);return{sources:arr(r.sources).map(x=>({source_key:String(x.source_key||''),source_name:String(x.source_name||''),adapter:String(x.adapter||''),ownership_signal:String(x.ownership_signal||''),active:Boolean(x.active),priority:num(x.priority),candidate_records:num(x.candidate_records),unique_businesses:num(x.unique_businesses),duplicate_records_merged:num(x.duplicate_records_merged),cities_covered:num(x.cities_covered),approved_businesses:num(x.approved_businesses),published_businesses:num(x.published_businesses),verification_conversion_pct:num(x.verification_conversion_pct),jobs:num(x.jobs),successful_jobs:num(x.successful_jobs),failed_jobs:num(x.failed_jobs),inserted_across_jobs:num(x.inserted_across_jobs),bad_job_rate_pct:num(x.bad_job_rate_pct),last_successful_crawl:String(x.last_successful_crawl||'')})),totals:{active_sources:num(t.active_sources),candidate_records:num(t.candidate_records),business_identities:num(t.business_identities),publication_ready:num(t.publication_ready),published_from_factory:num(t.published_from_factory)},generated_at:String(r.generated_at||'')}}
export async function fetchSourcePerformance(s:Client){const{data,error}=await rpc(s)('black_pages_staff_source_performance_snapshot',{});if(error||data==null)return{snapshot:null,error:error?.message||'Source performance unavailable.'};return{snapshot:parse(data),error:''}}
