import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import * as cheerio from "npm:cheerio@1.0.0";

type Candidate={id:string;business_name:string;city:string;state:string|null;category:string|null;website_url:string|null;external_source_url:string|null;source_category:string|null;source_subcategory:string|null;notes:string|null};
const clean=(v:string)=>String(v||'').replace(/\u200b/g,'').replace(/\s+/g,' ').trim();
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
function plausible(url:string){try{const u=new URL(url);return ['http:','https:'].includes(u.protocol)&&!/instagram\.com|facebook\.com|tiktok\.com|x\.com|twitter\.com/i.test(u.hostname)}catch{return false}}
async function readPage(url:string){const r=await fetch(url,{headers:{'User-Agent':'TheBlackPagesDeepEnrichment/1.0 (+business directory research)','Accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const html=await r.text(),$=cheerio.load(html);$('script,style,noscript,svg,nav,footer').remove();const title=clean($('title').text());const meta=clean($('meta[name="description"]').attr('content')||$('meta[property="og:description"]').attr('content')||'');const headings=$('h1,h2,h3').toArray().map(x=>clean($(x).text())).filter(Boolean).slice(0,20).join(' | ');let structured='';$('script[type="application/ld+json"]').each((_i,s)=>{if(structured.length>1800)return;try{const raw=$(s).html()||'';const obj=JSON.parse(raw);const values=Array.isArray(obj)?obj:[obj];for(const value of values){if(value&&typeof value==='object')structured+=' '+clean([value['@type'],value.name,value.description,value.servesCuisine,value.category].filter(Boolean).join(' '))}}catch{}});const body=clean($('body').text()).slice(0,4500);const text=clean([title,meta,headings,structured,body].join(' | ')).slice(0,6000);const email=(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||'';const phone=(text.match(/(?:\+?1[- .]?)?(?:\(\d{3}\)|\d{3})[- .]\d{3}[- .]\d{4}|\b1?\d{10}\b/)||[])[0]||'';return{url:r.url||url,text,email,phone}}
async function enrich(c:Candidate){const urls=[c.website_url,c.external_source_url].filter((u):u is string=>Boolean(u&&plausible(u))).filter((u,i,a)=>a.indexOf(u)===i).slice(0,2);if(!urls.length)throw new Error('no_fetchable_url');const settled=await Promise.allSettled(urls.map(readPage));const pages=settled.filter((x):x is PromiseFulfilledResult<{url:string;text:string;email:string;phone:string}>=>x.status==='fulfilled').map(x=>x.value);if(!pages.length)throw new Error('all_fetches_failed');const context=clean([`Business: ${c.business_name}`,`Location: ${c.city} ${c.state||''}`,`Existing category: ${c.category||''}`,`Source category: ${c.source_category||''}`,`Source subcategory: ${c.source_subcategory||''}`,...pages.map(p=>`Source ${p.url}: ${p.text}`)].join(' | ')).slice(0,6000);return{context,email:pages.find(p=>p.email)?.email||'',phone:pages.find(p=>p.phone)?.phone||'',pages:pages.length}}
Deno.serve(async request=>{if(request.method!=='POST')return json({error:'Method not allowed'},405);const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)return json({error:'Worker environment incomplete'},500);const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const token=request.headers.get('x-worker-token')||'';const {data:ok}=await supabase.rpc('black_pages_authorize_worker_token',{p_token:token});if(ok!==true)return json({error:'Unauthorized'},401);let payload:{limit?:number}={};try{payload=await request.json()}catch{}const limit=Math.min(100,Math.max(1,Number(payload.limit)||50));const {data:claim,error}=await supabase.rpc('black_pages_claim_deep_enrichment',{p_limit:limit});if(error)return json({error:error.message},500);const candidates=Array.isArray(claim?.candidates)?claim.candidates as Candidate[]:[];const settled=await Promise.allSettled(candidates.map(async c=>{try{const e=await enrich(c);await supabase.rpc('black_pages_complete_deep_enrichment',{p_candidate_id:c.id,p_context:e.context,p_phone:e.phone||null,p_email:e.email||null,p_error:null});return{id:c.id,ok:true,pages:e.pages}}catch(err){const message=err instanceof Error?err.message:'enrichment_failed';await supabase.rpc('black_pages_complete_deep_enrichment',{p_candidate_id:c.id,p_context:'',p_phone:null,p_email:null,p_error:message});return{id:c.id,ok:false,error:message}}}));const classification=await supabase.rpc('black_pages_context_classify_batch',{p_limit:30000});const verification=await supabase.rpc('black_pages_preverify_batch',{p_limit:30000});return json({ok:true,claimed:candidates.length,processed:settled.length,classification:classification.data,verification:verification.data,outcomes:settled.map(x=>x.status==='fulfilled'?x.value:{error:String(x.reason)})})});