import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import * as cheerio from "npm:cheerio@1.0.0";

type Job={id:string;source_key:string;request_url:string;city:string|null;state:string|null};
type Item={business_name:string;city:string;state:string;postal_code:string;address:string;source_category:string;source_subcategory:string;detail_url:string;website_url:string;instagram_handle:string;public_email:string;public_phone:string;description:string;source_key:string};
const clean=(v:string)=>String(v||'').replace(/\u200b/g,'').replace(/\s+/g,' ').trim();
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const abs=(href:string,base:string)=>{try{return new URL(href,base).toString()}catch{return''}};
const errorText=(e:unknown)=>e instanceof Error?e.message:(e&&typeof e==='object'&&'message'in e?String((e as {message?:unknown}).message):String(e||'chambermaster_failed'));
function phoneFrom(container:cheerio.Cheerio<any>,text:string){const tel=container.find('a[href^="tel:"]').first().attr('href')||'';if(tel){const d=tel.replace(/\D/g,'');if(d.length===10||d.length===11)return d.length===11?`+${d}`:d}const t=clean(text).replace(/\b\d{5}(?:-\d{4})?\b/g,' ');const m=t.match(/(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}/);return clean(m?.[0]||'')}
function locationFrom(text:string){const t=clean(text);const zip=t.match(/\b\d{5}(?:-\d{4})?\b/)?.[0]||'';if(!zip)return{address:'',city:'',state:'',postal_code:''};const idx=t.indexOf(zip);const before=t.slice(Math.max(0,idx-180),idx+zip.length);const stateMatch=before.match(/\b([A-Z]{2})\s+\d{5}(?:-\d{4})?\b/);const state=stateMatch?.[1]||'';let city='';let address='';if(state){const loc=new RegExp(`([^,\\n]{2,70})\\s+${state}\\s+${zip.replace('-','\\-')}$`,'i').exec(before);if(loc)city=clean(loc[1].split(/\s{2,}|,/).pop()||'');address=clean(before)}return{address,city,state,postal_code:zip}}
function externalSite(container:cheerio.Cheerio<any>,base:string){let out='';container.find('a[href]').each((_i,a)=>{if(out)return;const href=abs(container.find(a).attr('href')||'',base),label=clean(container.find(a).text()).toLowerCase();if(!href)return;try{const u=new URL(href),b=new URL(base);if(u.hostname===b.hostname||/google\.|facebook\.com|instagram\.com|linkedin\.com|mailto:|tel:/i.test(href))return;if(/website|visit|learn more|company site/.test(label))out=href}catch{}});return out}
function parseList(html:string,job:Job){const $=cheerio.load(html),items:Item[]=[];const seen=new Set<string>();$('a[href*="/list/member/"]').each((_i,a)=>{const link=$(a),detail=abs(link.attr('href')||'',job.request_url);if(!detail||seen.has(detail))return;const name=clean(link.text());if(!name||name.length>220||/more info|details|website|member directory|search/i.test(name))return;let card=link.closest('.mn-listing,.mn-item,.card,article,li,[class*="member"],[class*="listing"]');if(!card.length||clean(card.text()).length>5000){card=link.parent();for(let d=0;d<7&&card.length;d++){const t=clean(card.text());if(t.length>name.length&&t.length<5000&&(/\d{5}/.test(t)||/\(\d{3}\)/.test(t)))break;card=card.parent()}}const full=clean(card.text());if(!full||full.length>5000)return;seen.add(detail);const loc=locationFrom(full);const phone=phoneFrom(card,full);const email=(card.find('a[href^="mailto:"]').first().attr('href')||'').replace(/^mailto:/i,'').split('?')[0];const website=externalSite(card,job.request_url);const category=clean(card.find('[class*="category"],.mn-category').first().text());items.push({business_name:name,city:loc.city||job.city||'',state:loc.state||job.state||'',postal_code:loc.postal_code,address:loc.address,source_category:category,source_subcategory:'',detail_url:detail,website_url:website,instagram_handle:'',public_email:email,public_phone:phone,description:clean(full.replace(name,'').replace(loc.address,'')).slice(0,1000),source_key:detail.slice(0,180)})});return items.slice(0,500)}
async function enrichDetail(item:Item){try{const r=await fetch(item.detail_url,{headers:{'User-Agent':'TheBlackPagesChamberMaster/1.0 (+public Black Chamber member directory indexing)','Accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(12000)});if(!r.ok)return item;const $=cheerio.load(await r.text()),body=clean($('main').text()||$('body').text());const loc=locationFrom(body);const category=clean($('[class*="category"],.mn-category').first().text());const website=externalSite($('body'),item.detail_url);const email=($('a[href^="mailto:"]').first().attr('href')||'').replace(/^mailto:/i,'').split('?')[0];const phone=phoneFrom($('body'),body);const desc=clean($('meta[name="description"]').attr('content')||$('[class*="description"],.mn-description').first().text()).slice(0,1000);return{...item,city:item.city||loc.city,state:item.state||loc.state,postal_code:item.postal_code||loc.postal_code,address:item.address||loc.address,source_category:item.source_category||category,website_url:item.website_url||website,public_email:item.public_email||email,public_phone:item.public_phone||phone,description:desc||item.description}}catch{return item}}
async function process(supabase:ReturnType<typeof createClient>,job:Job){try{const r=await fetch(job.request_url,{headers:{'User-Agent':'TheBlackPagesChamberMaster/1.0 (+public Black Chamber member directory indexing)','Accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(18000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const base=parseList(await r.text(),job);const items:Item[]=[];for(let i=0;i<base.length;i+=10){const settled=await Promise.allSettled(base.slice(i,i+10).map(enrichDetail));items.push(...settled.map((x,j)=>x.status==='fulfilled'?x.value:base[i+j]))}const{data,error}=await supabase.rpc('black_pages_complete_external_job_fast',{p_job_id:job.id,p_items:items,p_error:null});if(error)throw new Error(error.message);return{job_id:job.id,source:job.source_key,found:items.length,result:data}}catch(e){const message=errorText(e);await supabase.rpc('black_pages_complete_external_job_fast',{p_job_id:job.id,p_items:[],p_error:message});return{job_id:job.id,source:job.source_key,error:message}}}
Deno.serve(async request=>{if(request.method!=='POST')return json({error:'Method not allowed'},405);const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)return json({error:'Worker environment incomplete'},500);const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),token=request.headers.get('x-worker-token')||'';const{data:ok}=await supabase.rpc('black_pages_authorize_worker_token',{p_token:token});if(ok!==true)return json({error:'Unauthorized'},401);let body:{jobs?:number}={};try{body=await request.json()}catch{}const{data:claim,error}=await supabase.rpc('black_pages_claim_adapter_jobs',{p_adapter:'chambermaster_v1',p_limit:Math.min(6,Math.max(1,Number(body.jobs)||2))});if(error)return json({error:error.message},500);const jobs=Array.isArray(claim?.jobs)?claim.jobs as Job[]:[];const settled=await Promise.allSettled(jobs.map(j=>process(supabase,j)));await supabase.rpc('black_pages_auto_classify_batch',{p_limit:30000});await supabase.rpc('black_pages_context_classify_batch',{p_limit:30000});await supabase.rpc('black_pages_preverify_batch',{p_limit:30000});return json({ok:true,claimed:jobs.length,processed:settled.length,outcomes:settled.map(x=>x.status==='fulfilled'?x.value:{error:String(x.reason)})})});