import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import * as cheerio from "npm:cheerio@1.0.0";

type Job={id:string;source_key:string;request_url:string};
type Item={business_name:string;city:string;state:string;postal_code:string;address:string;source_category:string;source_subcategory:string;detail_url:string;website_url:string;instagram_handle:string;public_email:string;public_phone:string;description:string;source_key:string};
const clean=(v:string)=>String(v||'').replace(/\u200b/g,'').replace(/\s+/g,' ').trim();
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const abs=(href:string,base:string)=>{try{return new URL(href,base).toString()}catch{return''}};
const phone=(text:string)=>clean(text).match(/(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}/)?.[0]||'';
const errorMessage=(e:unknown)=>e instanceof Error?e.message:(e&&typeof e==='object'&&'message'in e?String((e as {message?:unknown}).message):String(e||'regional_brw_failed'));
const ig=(href:string)=>{try{const u=new URL(href);return /instagram\.com$/i.test(u.hostname.replace(/^www\./,''))?(u.pathname.split('/').filter(Boolean)[0]||''):''}catch{return''}};
function parseAddress(text:string,cityHint='',stateHint=''){const raw=clean(text);let city=cityHint,state=stateHint,postal_code='';const m=raw.match(/(?:^|,|\s)([A-Za-z .'-]+),?\s+([A-Z]{2})\s+(\d{5}(?:-\d{4})?)\b/i);if(m){city=clean(m[1]).replace(/^.*\d\s+/,'');state=m[2].toUpperCase();postal_code=m[3]}return{address:raw,city,state,postal_code}}
function site(container:cheerio.Cheerio<any>,base:string){let out='';container.find('a[href]').each((_i,a)=>{if(out)return;const href=abs(container.find(a).attr('href')||'',base);if(!href||/facebook\.com|instagram\.com|youtube\.com|doordash|ubereats|grubhub|eventbrite|mailto:|tel:/i.test(href))return;try{const u=new URL(href),b=new URL(base);if(u.hostname===b.hostname)return;if(/^https?:/.test(href))out=href}catch{}});return out}
function headingItems($:cheerio.CheerioAPI,base:string,defaultCity:string,defaultState:string,source:string){const items:Item[]=[];const seen=new Set<string>();$('h2,h3,h4,h5').each((_i,h)=>{const heading=$(h),name=clean(heading.text());if(!name||name.length>120||/participating|restaurant week|special|events|about|contact|click|menu|2026|2025|sponsor|what is|cookies|privacy|terms|copyright|sign up|drop us a line/i.test(name))return;if(seen.has(name.toLowerCase()))return;let container=heading.parent();for(let d=0;d<5&&container.length;d++){const t=clean(container.text());if(t.length>=name.length+10&&t.length<2200)break;container=container.parent()}const text=clean(container.text());const addressMatch=text.match(/\d{1,6}\s+[^|]{2,120}?(?:,|\|)\s*[A-Za-z .'-]+,?\s+[A-Z]{2}\s+\d{5}/i)||text.match(/\d{1,6}\s+[^|]{2,120}?\s+[A-Za-z .'-]+,?\s+[A-Z]{2}\s+\d{5}/i);const parsed=parseAddress(addressMatch?.[0]||'',defaultCity,defaultState);const web=site(container,base);const instagram=ig(container.find('a[href*="instagram.com"]').first().attr('href')||'');const detail=abs(heading.find('a[href]').first().attr('href')||'',base)||base+'#'+encodeURIComponent(name.toLowerCase().replace(/\s+/g,'-'));const categoryHint=(text.match(/(?:Cuisine|Category)\s*:?\s*([A-Za-z &/-]{3,60})/i)?.[1]||'').trim();seen.add(name.toLowerCase());items.push({business_name:name,city:parsed.city||defaultCity,state:parsed.state||defaultState,postal_code:parsed.postal_code,address:parsed.address,source_category:'Restaurants, Food & Beverages',source_subcategory:categoryHint,detail_url:detail,website_url:web,instagram_handle:instagram,public_email:(text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/i)||[])[0]||'',public_phone:phone(text),description:clean(text.replace(name,'').replace(parsed.address,'')).slice(0,1000),source_key:(source+':'+name.toLowerCase().replace(/[^a-z0-9]+/g,'-')).slice(0,180)})});return items}
function parseMemphis(html:string,job:Job){const $=cheerio.load(html);return headingItems($,job.request_url,'Memphis','TN',job.source_key).filter(x=>x.address||x.website_url||x.public_phone).filter(x=>!/daily brunch|daily special|make reservations|order online|pick up order/i.test(x.business_name)).slice(0,100)}
function parseLongBeach(html:string,job:Job){const $=cheerio.load(html);return headingItems($,job.request_url,'Long Beach','CA',job.source_key).filter(x=>!/this website uses cookies|fresh off the yacht catering/i.test(x.business_name)||x.website_url||x.public_phone).slice(0,150)}
function externalFromCell(cell:cheerio.Cheerio<any>,base:string){let out='';cell.find('a[href]').each((_i,a)=>{if(out)return;const href=abs(cell.find(a).attr('href')||'',base);if(!href)return;try{const u=new URL(href),b=new URL(base);if(u.hostname!==b.hostname&&/^https?:/.test(href))out=href}catch{}});if(out)return out;const text=clean(cell.text()).replace(/^http:\/\/https:\/\//i,'https://');return /^https?:\/\//i.test(text)?text:''}
function parseSanAntonio(html:string,job:Job){const $=cheerio.load(html),items:Item[]=[];let target:cheerio.Cheerio<any>|null=null;$('table').each((_i,t)=>{if(target)return;const header=clean($(t).find('tr').first().text());if(/participant/i.test(header)&&/cuisine/i.test(header)&&/website/i.test(header))target=$(t)});if(!target)return items;target.find('tr').each((_i,tr)=>{const cells=$(tr).find('th,td').toArray().map(x=>$(x));if(cells.length<3)return;const name=clean(cells[0].text()),cuisine=clean(cells[1].text()),websiteText=clean(cells[2].text());if(!name||/participant/i.test(name))return;const website=/\bN\/?A\b/i.test(websiteText)?'':externalFromCell(cells[2],job.request_url);items.push({business_name:name,city:'San Antonio',state:'TX',postal_code:'',address:'',source_category:'Restaurants, Food & Beverages',source_subcategory:cuisine,detail_url:job.request_url+'#'+encodeURIComponent(name.toLowerCase().replace(/\s+/g,'-')),website_url:website,instagram_handle:'',public_email:'',public_phone:'',description:cells.slice(3).map(c=>clean(c.text())).join(' ').slice(0,1000),source_key:(job.source_key+':'+name.toLowerCase().replace(/[^a-z0-9]+/g,'-')).slice(0,180)})});return items.slice(0,100)}
function parse(html:string,job:Job){if(job.source_key==='memphis_black_restaurant_week')return parseMemphis(html,job);if(job.source_key==='long_beach_black_restaurant_week')return parseLongBeach(html,job);if(job.source_key==='san_antonio_black_restaurant_week')return parseSanAntonio(html,job);return []}
async function processJob(supabase:ReturnType<typeof createClient>,job:Job){try{const r=await fetch(job.request_url,{headers:{'User-Agent':'TheBlackPagesRegionalBRW/1.1 (+public Black-owned food directory indexing)','Accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(18000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const items=parse(await r.text(),job);const {data,error}=await supabase.rpc('black_pages_complete_external_job',{p_job_id:job.id,p_items:items,p_error:null});if(error)throw error;return{job_id:job.id,source:job.source_key,found:items.length,result:data}}catch(e){const message=errorMessage(e);await supabase.rpc('black_pages_complete_external_job',{p_job_id:job.id,p_items:[],p_error:message});return{job_id:job.id,source:job.source_key,error:message}}}
Deno.serve(async request=>{if(request.method!=='POST')return json({error:'Method not allowed'},405);const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)return json({error:'Worker environment incomplete'},500);const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const token=request.headers.get('x-worker-token')||'';const {data:ok}=await supabase.rpc('black_pages_authorize_worker_token',{p_token:token});if(ok!==true)return json({error:'Unauthorized'},401);let payload:{jobs?:number}={};try{payload=await request.json()}catch{}const {data:claim,error}=await supabase.rpc('black_pages_claim_adapter_jobs',{p_adapter:'regional_brw_v2',p_limit:Math.min(10,Math.max(1,Number(payload.jobs)||3))});if(error)return json({error:error.message},500);const jobs=Array.isArray(claim?.jobs)?claim.jobs as Job[]:[];const settled=await Promise.allSettled(jobs.map(j=>processJob(supabase,j)));return json({ok:true,claimed:jobs.length,processed:settled.length,outcomes:settled.map(x=>x.status==='fulfilled'?x.value:{error:String(x.reason)})})});