import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, ExternalLink, RefreshCw, Search, ShieldAlert, ShieldCheck } from 'lucide-react'
import type { SupabaseClient } from '@supabase/supabase-js'
import type { Database } from '../lib/database.types.ts'
import { fetchFirst100ReviewPack,type ReviewPackSnapshot,type ReviewRecommendation } from '../services/reviewPack.ts'
import { submitIdentityBatchReview } from '../services/identityVerification.ts'
import './First100ReviewPack.css'

export function First100ReviewPack({supabase}:{supabase:SupabaseClient<Database>}){
 const[snapshot,setSnapshot]=useState<ReviewPackSnapshot|null>(null);const[filter,setFilter]=useState<ReviewRecommendation|'all'>('all');const[query,setQuery]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState('');const[error,setError]=useState('');const[success,setSuccess]=useState('')
 async function load(){setLoading(true);setError('');const r=await fetchFirst100ReviewPack(supabase);if(r.error||!r.snapshot)setError(r.error||'Review pack unavailable.');else setSnapshot(r.snapshot);setLoading(false)}
 useEffect(()=>{void load()},[]) // eslint-disable-line react-hooks/exhaustive-deps
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return(snapshot?.items||[]).filter(i=>(filter==='all'||i.recommended_decision===filter)&&(!q||`${i.source_snapshot.business_name} ${i.source_snapshot.city} ${i.source_snapshot.source_names.join(' ')}`.toLowerCase().includes(q)))},[snapshot,filter,query])
 async function applyGroup(decision:ReviewRecommendation){if(busy)return;const items=(snapshot?.items||[]).filter(i=>i.recommended_decision===decision);if(!items.length)return;const label=decision==='approve'?'approve ownership evidence':decision==='reject'?'reject these ineligible identities':'route these businesses for independent ownership corroboration';if(!window.confirm(`Apply recommendation to ${items.length} businesses: ${label}? This does not publish listings.`))return;setBusy(decision);setError('');setSuccess('');const reason=decision==='approve'?'First-100 evidence pack: Black Restaurant Week provides explicit public Black-owned culinary/business evidence. Approve ownership evidence only; publication remains separate.':decision==='reject'?'First-100 evidence pack: reviewed institutional/corporate ownership evidence is incompatible with Black-owned business listing eligibility.':'First-100 evidence pack: Black Chamber membership alone is insufficient to establish Black ownership; require independent ownership corroboration.';const r=await submitIdentityBatchReview(supabase,{identityIds:items.map(i=>i.identity_id),decision,reason});if(r.error)setError(r.error);else setSuccess(`${Number(r.result?.identities_reviewed||items.length)} businesses processed. No public listing was auto-published.`);setBusy('')}
 return <section className="review-pack">
  <div className="review-pack-head"><div><span><ShieldCheck size={14}/> FIRST 100 REVIEW PACK</span><h2>The evidence work is done. Staff applies the audited decisions.</h2><p>The original Ready queue over-weighted chamber membership. This pack separates explicit Black-owned evidence from chamber-only corroboration needs and verified institutional false positives.</p></div><button onClick={()=>void load()} disabled={loading}><RefreshCw size={15} className={loading?'spin':''}/></button></div>
  <div className="review-pack-kpis"><button className={filter==='approve'?'active approve':''} onClick={()=>setFilter(filter==='approve'?'all':'approve')}><small>Recommend approve</small><strong>{snapshot?.counts.approve||0}</strong><span>Explicit BRW ownership evidence</span></button><button className={filter==='needs_more_evidence'?'active':''} onClick={()=>setFilter(filter==='needs_more_evidence'?'all':'needs_more_evidence')}><small>Corroborate</small><strong>{snapshot?.counts.needs_more_evidence||0}</strong><span>Chamber membership needs proof</span></button><button className={filter==='reject'?'active reject':''} onClick={()=>setFilter(filter==='reject'?'all':'reject')}><small>Recommend reject</small><strong>{snapshot?.counts.reject||0}</strong><span>Institutional/corporate mismatch</span></button></div>
  <div className="review-pack-actions"><button className="approve" disabled={!!busy||!snapshot?.counts.approve} onClick={()=>void applyGroup('approve')}><CheckCircle2 size={14}/>Apply {snapshot?.counts.approve||0} approvals</button><button disabled={!!busy||!snapshot?.counts.needs_more_evidence} onClick={()=>void applyGroup('needs_more_evidence')}><ShieldAlert size={14}/>Send {snapshot?.counts.needs_more_evidence||0} to corroboration</button><button className="reject" disabled={!!busy||!snapshot?.counts.reject} onClick={()=>void applyGroup('reject')}><AlertTriangle size={14}/>Apply {snapshot?.counts.reject||0} rejections</button></div>
  <label className="review-pack-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the 100-business evidence pack"/></label>
  {error&&<div className="review-pack-message error"><AlertTriangle size={14}/>{error}</div>}{success&&<div className="review-pack-message success"><CheckCircle2 size={14}/>{success}</div>}
  <div className="review-pack-list">{loading&&!snapshot?<div className="review-pack-empty">Loading review recommendations…</div>:visible.slice(0,100).map(i=><article key={i.identity_id}><b>#{i.rank}</b><div><strong>{i.source_snapshot.business_name}</strong><span>{i.source_snapshot.city}{i.source_snapshot.state?`, ${i.source_snapshot.state}`:''}</span><small>{i.recommendation_reason}</small><div>{i.source_snapshot.source_names.map(s=><i key={s}>{s}</i>)}</div>{i.source_snapshot.evidence_urls[0]&&<a href={i.source_snapshot.evidence_urls[0]} target="_blank" rel="noreferrer">Open evidence <ExternalLink size={11}/></a>}</div><em className={i.recommended_decision}>{i.recommended_decision.replaceAll('_',' ')}</em></article>)}{!loading&&!visible.length&&<div className="review-pack-empty">No recommendations match this filter.</div>}</div>
  <p className="review-pack-safety"><ShieldCheck size={13}/>These buttons call the existing authenticated owner/admin/editor review function. They cannot publish a directory listing.</p>
 </section>
}
