import { useEffect, useMemo, useState } from 'react'
import { AlertTriangle, CheckCircle2, ExternalLink, FileCheck2, RefreshCw, Send } from 'lucide-react'
import type { SupabaseClient } from '@supabase/supabase-js'
import type { Database } from '../lib/database.types.ts'
import { fetchPublicationSnapshot,publishDraft,type PublicationDraft,type PublicationSnapshot } from '../services/publication.ts'
import './PublicationFactory.css'

type Tab='ready'|'draft'|'published'
export function PublicationFactory({supabase}:{supabase:SupabaseClient<Database>}){
 const[snapshot,setSnapshot]=useState<PublicationSnapshot|null>(null);const[tab,setTab]=useState<Tab>('ready');const[selected,setSelected]=useState<PublicationDraft|null>(null);const[reason,setReason]=useState('');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('')
 async function load(){setLoading(true);setError('');const r=await fetchPublicationSnapshot(supabase,400);if(r.error||!r.snapshot)setError(r.error||'Publication factory unavailable.');else setSnapshot(r.snapshot);setLoading(false)}
 useEffect(()=>{void load()},[]) // eslint-disable-line react-hooks/exhaustive-deps
 const rows=useMemo(()=>snapshot?.drafts.filter(x=>x.status===tab)||[],[snapshot,tab])
 async function publish(){if(!selected||!reason.trim()||busy)return;setBusy(true);setError('');setSuccess('');const r=await publishDraft(supabase,selected.id,reason.trim());if(r.error)setError(r.error);else{setSuccess(`${selected.business_name} published to THE BLACK PAGES.`);setSelected(null);setReason('');await load()}setBusy(false)}
 return <section className="publication-factory">
  <div className="pub-head"><div><span><FileCheck2 size={14}/> PUBLICATION FACTORY</span><h2>Approved businesses become complete draft profiles.</h2><p>Drafts are generated from the strongest canonical business record plus every attached source. Nothing publishes until a staff member performs the final publication action.</p></div><button onClick={()=>void load()} disabled={loading}><RefreshCw size={15} className={loading?'spin':''}/></button></div>
  <div className="pub-kpis"><button className={tab==='ready'?'active':''} onClick={()=>{setTab('ready');setSelected(null)}}><small>Ready</small><strong>{snapshot?.counts.ready||0}</strong></button><button className={tab==='draft'?'active':''} onClick={()=>{setTab('draft');setSelected(null)}}><small>Needs fields</small><strong>{snapshot?.counts.draft||0}</strong></button><button className={tab==='published'?'active':''} onClick={()=>{setTab('published');setSelected(null)}}><small>Published</small><strong>{snapshot?.counts.published||0}</strong></button><article><small>Avg completeness</small><strong>{snapshot?.counts.avg_completeness||0}%</strong></article></div>
  {error&&<div className="pub-message error"><AlertTriangle size={15}/>{error}</div>}{success&&<div className="pub-message success"><CheckCircle2 size={15}/>{success}</div>}
  <div className="pub-grid">{loading&&!snapshot?<div className="pub-empty">Building publication drafts…</div>:rows.slice(0,120).map(d=><article key={d.id} className={selected?.id===d.id?'selected':''} onClick={()=>setSelected(d)}><div className="pub-title"><div><strong>{d.business_name}</strong><span>{d.city}, {d.state}</span></div><b>{d.completeness_score}%</b></div><div className="pub-meta"><span>{d.category}</span>{d.subcategory&&<span>{d.subcategory}</span>}{d.source_names.slice(0,2).map(x=><i key={x}>{x}</i>)}</div><p>{d.short_description||'Description still needed.'}</p><div className="pub-contact">{d.address&&<span>{d.address}</span>}{d.phone&&<span>{d.phone}</span>}{d.website_url&&<span>Website</span>}</div>{d.missing_fields.length>0&&<small>Missing: {d.missing_fields.join(', ')}</small>}<div className="pub-evidence">{d.evidence_urls.slice(0,2).map((u,i)=><a key={`${u}-${i}`} href={u} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>Evidence {i+1}<ExternalLink size={11}/></a>)}</div></article>)}{!loading&&rows.length===0&&<div className="pub-empty">No {tab} publication drafts yet.</div>}</div>
  {selected&&tab==='ready'&&<div className="pub-final"><div><strong>Final publication: {selected.business_name}</strong><small>This creates the public listing. Review the evidence and profile before publishing.</small></div><textarea value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required final publication reason / QA note" rows={3}/><button onClick={()=>void publish()} disabled={!reason.trim()||busy}><Send size={15}/>{busy?'PUBLISHING…':'PUBLISH TO DIRECTORY'}</button></div>}
 </section>
}
