import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import * as cheerio from "npm:cheerio@1.0.0";

type Job={id:string;source_key:string;request_url:string;city:string|null;state:string|null};
type Item={business_name:string;city:string;state:string;postal_code:string;address:string;source_category:string;source_subcategory:string;detail_url:string;website_url:string;instagram_handle:string;public_email:string;public_phone:string;description:string;source_key:string};
const clean=(v:string)=>String(v||'').replace(/\u200b/g,'').replace(/\s+/g,' ').trim();
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
const abs=(href:string,base:string)=>{try{return new URL(href,base).toString()}catch{return''}};
const err=(e:unknown)=>e instanceof Error?e.message:(e&&typeof e==='object'&&'message'in e?String((e as {message?:unknown}).message):String(e||'growthzone_failed'));
function parseAddress(raw:string,cityHint='',stateHint=''){const text=clean(raw);let city=cityHint,state=stateHint,postal_code='';const m=text.match(/(?:^|,\s*)([^,]+),\s*([A-Z]{2})\s+(\d{5}(?:-\d{4})?)\b/i);if(m){city=clean(m[1]);state=m[2].toUpperCase();postal_code=m[3]}return{address:text,city,state,postal_code}}
function safePhone(container:cheerio.Cheerio<any>,text:string){const tel=container.find('a[href^="tel:"]').first().attr('href')||'';if(tel){const d=tel.replace(/\D/g,'');if(d.length===10||d.length===11)return d.length===11?`+${d}`:d}const sanitized=clean(text).replace(/\b\d{5}(?:-\d{4})?\b/g,' ');const m=sanitized.match(/(?:\+?1[- .]?)?(?:\(\d{3}\)|\d{3})[- .]\d{3}[- .]\d{4}|\b1?\d{10}\b/);return clean(m?.[0]||'')}
function externalSite(container:cheerio.Cheerio<any>,base:string){let out='';container.find('a[href]').each((_i,a)=>{if(out)return;const el=container.find(a),label=clean(el.text()).toLowerCase(),href=abs(el.attr('href')||'',base);if(!href)return;try{const u=new URL(href),b=new URL(base);if(u.hostname===b.hostname||/google\.|facebook\.com|instagram\.com|linkedin\.com|mailto:|tel:/i.test(href))return;if(/visit website|website/.test(label))out=href}catch{}});return out}
function parse(html:string,job:Job){const $=cheerio.load(html),items:Item[]=[];const seen=new Set<string>();$('a[href*="/Details/"]').each((_i,a)=>{const link=$(a),detail=abs(link.attr('href')||'',job.request_url);if(!detail||seen.has(detail))return;let card=link.closest('[class*="gz-list-card"],[class*="card-wrapper"],[class*="gz-card"],article,li');if(!card.length||card.text().length>6500){card=link.parent();for(let d=0;d<8&&card.length;d++){const t=clean(card.text());if(/More Details/i.test(t)&&t.length<6500)break;card=card.parent()}}let name='';card.find('a[href*="/Details/"]').each((_j,n)=>{if(name)return;const t=clean($(n).text());if(t&&!/more details/i.test(t))name=t});if(!name)name=clean(card.find('h2,h3,h4,h5').first().text());if(!name||name.length>220||/member directory|back to search|more details/i.test(name))return;seen.add(detail);const full=clean(card.text());const map=card.find('a[href*="google.com/maps"],a[href*="maps.google"]').filter((_j,n)=>/\d/.test(clean($(n).text()))).first();let addr=clean(map.text());if(!addr)addr=full.match(/(?:P\.?O\.? Box\s+\d+|\d{1,6}\s+[^|]{2,130}?),\s*[^,]{2,60},\s*[A-Z]{2}\s+\d{5}(?:-\d{4})?/i)?.[0]||'';const loc=parseAddress(addr,job.city||'',job.state||'');const cats=card.find('a[href*="/Search/"],a[href*="/directory/Search"],a[href*="/member-directory/Search"]').toArray().map(n=>clean($(n).text())).filter(t=>t&&!/search/i.test(t));const sourceCategory=[...new Set(cats)].join(' | ').slice(0,240);const website=externalSite(card,job.request_url);const emailHref=card.find('a[href^="mailto:"]').first().attr('href')||'';const phone=safePhone(card,full);items.push({business_name:name,city:loc.city,state:loc.state,postal_code:loc.postal_code,address:loc.address,source_category:sourceCategory,source_subcategory:'',detail_url:detail,website_url:website,instagram_handle:'',public_email:emailHref.replace(/^mailto:/i,'').split('?')[0],public_phone:phone,description:clean(full.replace(name,'').replace(addr,'').replace(/Send Email|Visit Website|More Details/gi,' ')).slice(0,1000),source_key:detail.slice(0,180)})});return items.slice(0,1000)}
async function process(supabase:ReturnType<typeof createClient>,job:Job){try{const r=await fetch(job.request_url,{headers:{'User-Agent':'TheBlackPagesGrowthZone/2.1 (+public Black Chamber directory indexing)','Accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`HTTP ${r.status}`);const items=parse(await r.text(),job);const {data,error}=await supabase.rpc('black_pages_complete_external_job_fast',{p_job_id:job.id,p_items:items,p_error:null});if(error)throw error;return{job_id:job.id,source:job.source_key,found:items.length,result:data}}catch(e){const message=err(e);await supabase.rpc('black_pages_complete_external_job_fast',{p_job_id:job.id,p_items:[],p_error:message});return{job_id:job.id,source:job.source_key,error:message}}}
Deno.serve(async request=>{if(request.method!=='POST')return json({error:'Method not allowed'},405);const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)return json({error:'Worker environment incomplete'},500);const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const token=request.headers.get('x-worker-token')||'';const {data:ok}=await supabase.rpc('black_pages_authorize_worker_token',{p_token:token});if(ok!==true)return json({error:'Unauthorized'},401);let payload:{jobs?:number}={};try{payload=await request.json()}catch{}const {data:claim,error}=await supabase.rpc('black_pages_claim_adapter_jobs',{p_adapter:'growthzone_v2',p_limit:Math.min(10,Math.max(1,Number(payload.jobs)||3))});if(error)return json({error:error.message},500);const jobs=Array.isArray(claim?.jobs)?claim.jobs as Job[]:[];const settled=await Promise.allSettled(jobs.map(j=>process(supabase,j)));const outcomes=settled.map(x=>x.status==='fulfilled'?x.value:{error:String(x.reason)});const classification1=await supabase.rpc('black_pages_auto_classify_batch',{p_limit:30000});const classification2=await supabase.rpc('black_pages_context_classify_batch',{p_limit:30000});const verification=await supabase.rpc('black_pages_preverify_batch',{p_limit:30000});return json({ok:true,claimed:jobs.length,processed:settled.length,outcomes,classification:{primary:classification1.data,context:classification2.data},verification:verification.data})});