import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";

type Candidate={id:string;business_name:string;city:string;state:string|null;category:string|null;subcategory?:string|null;website_url:string|null;instagram_handle:string|null;public_email:string|null;public_phone:string|null;priority_score:number|string};
type FetchEvidence={reachable:boolean;checked_url:string|null;final_url:string|null;fetch_status:number|null;content_type:string|null;page_title:string|null;explicit_ownership_evidence:boolean;ownership_evidence:string[];error?:string;duration_ms:number};
const workerName="black-pages-research-worker";
const maxBodyBytes=300_000;
const concurrency=20;
const ownershipPatterns=[/\b(?:proudly\s+)?black[\s-]+owned\b/gi,/\bblack[\s-]+woman[\s-]+owned\b/gi,/\bblack[\s-]+women[\s-]+owned\b/gi,/\bblack[\s-]+family[\s-]+owned\b/gi,/\bblack[\s-]+veteran[\s-]+owned\b/gi,/\bblack[\s-]+(?:founded|led|operated)\b/gi,/\bafrican[\s-]+american[\s-]+(?:owned|founded|led|operated)\b/gi];
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}})}
function privateIpv4(host:string){const p=host.split('.').map(Number);if(p.length!==4||p.some(v=>!Number.isInteger(v)||v<0||v>255))return false;return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)}
function publicUrl(raw:string){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol))throw new Error('unsupported_protocol');const h=u.hostname.toLowerCase().replace(/\.$/,'');if(!h||h==='localhost'||h.endsWith('.localhost')||h.endsWith('.local')||h.endsWith('.internal')||h.includes(':')||privateIpv4(h))throw new Error('blocked_address');u.username='';u.password='';return u}
async function readLimited(r:Response){if(!r.body)return '';const rd=r.body.getReader(),dec=new TextDecoder();let total=0,out='';try{while(total<maxBodyBytes){const {value,done}=await rd.read();if(done)break;if(!value)continue;const rem=maxBodyBytes-total,s=value.byteLength>rem?value.slice(0,rem):value;out+=dec.decode(s,{stream:true});total+=s.byteLength;if(s.byteLength<value.byteLength)break}out+=dec.decode()}finally{await rd.cancel().catch(()=>undefined)}return out}
function text(html:string){return html.replace(/<!--[\s\S]*?-->/g,' ').replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<noscript\b[^>]*>[\s\S]*?<\/noscript>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim()}
function title(html:string){const m=html.match(/<title\b[^>]*>([\s\S]*?)<\/title>/i);return m?text(m[1]).slice(0,240):null}
function evidence(t:string){const s=new Set<string>();for(const p of ownershipPatterns){p.lastIndex=0;let m:RegExpExecArray|null;while((m=p.exec(t))&&s.size<5)s.add(t.slice(Math.max(0,m.index-90),Math.min(t.length,m.index+m[0].length+120)).trim().slice(0,320))}return [...s]}
function evidenceLinks(html:string,base:URL){const links=new Set<string>(),re=/href\s*=\s*["']([^"'#]+)["']/gi;let m:RegExpExecArray|null;while((m=re.exec(html))&&links.size<4){if(!/(about|our[-_ ]?story|founder|ownership|mission|who[-_ ]?we[-_ ]?are)/i.test(m[1]))continue;try{const t=publicUrl(new URL(m[1],base).toString());if(t.hostname===base.hostname)links.add(t.toString())}catch{}}return [...links]}
async function fetchText(target:URL,timeout=6000){let current=target,response:Response|null=null;for(let redirect=0;redirect<=4;redirect++){response=await fetch(current,{method:'GET',redirect:'manual',signal:AbortSignal.timeout(timeout),headers:{'User-Agent':'TheBlackPagesResearchBot/3.0 (+public business verification)','Accept':'text/html,application/xhtml+xml;q=0.9,text/plain;q=0.8,*/*;q=0.2'}});if([301,302,303,307,308].includes(response.status)){const loc=response.headers.get('location');if(!loc)break;current=publicUrl(new URL(loc,current).toString());continue}break}if(!response)throw new Error('no_response');const ct=response.headers.get('content-type');const html=!ct||/text|html|xhtml|json/i.test(ct)?await readLimited(response):'';return{response,html,current,ct}}
async function inspect(c:Candidate):Promise<FetchEvidence>{const started=Date.now();if(!c.website_url)return{reachable:false,checked_url:null,final_url:null,fetch_status:null,content_type:null,page_title:null,explicit_ownership_evidence:false,ownership_evidence:[],error:'no_public_endpoint',duration_ms:Date.now()-started};let start:URL;try{start=publicUrl(c.website_url)}catch(e){return{reachable:false,checked_url:c.website_url,final_url:null,fetch_status:null,content_type:null,page_title:null,explicit_ownership_evidence:false,ownership_evidence:[],error:e instanceof Error?e.message:'invalid_url',duration_ms:Date.now()-started}}try{const first=await fetchText(start);let found=evidence(text(first.html)),url=first.current.toString();if(!found.length&&first.response.ok&&/html|xhtml/i.test(first.ct||'text/html')&&first.current.hostname!=='www.instagram.com'){for(const link of evidenceLinks(first.html,first.current).slice(0,2)){try{const detail=await fetchText(publicUrl(link),4500),f=evidence(text(detail.html));if(f.length){found=f;url=detail.current.toString();break}}catch{}}}return{reachable:first.response.status>=200&&first.response.status<500,checked_url:c.website_url,final_url:url,fetch_status:first.response.status,content_type:first.ct,page_title:title(first.html),explicit_ownership_evidence:found.length>0,ownership_evidence:found,duration_ms:Date.now()-started}}catch(e){return{reachable:false,checked_url:c.website_url,final_url:start.toString(),fetch_status:null,content_type:null,page_title:null,explicit_ownership_evidence:false,ownership_evidence:[],error:e instanceof Error?e.message.slice(0,300):'fetch_failed',duration_ms:Date.now()-started}}}
Deno.serve(async request=>{if(request.method!=='POST')return json({error:'Method not allowed'},405);const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)return json({error:'Worker environment is incomplete'},500);const sb=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const token=request.headers.get('x-worker-token')||'';const {data:authorized,error:authError}=await sb.rpc('black_pages_authorize_worker_token',{p_token:token});if(authError||authorized!==true)return json({error:'Unauthorized'},401);let payload:{limit?:number}={};try{payload=await request.json()}catch{}const limit=Math.min(100,Math.max(1,Number(payload.limit)||100));const {data:claim,error:claimError}=await sb.rpc('black_pages_claim_research_batch',{p_limit:limit,p_worker:workerName});if(claimError)return json({error:claimError.message},500);const runId=String(claim?.run_id||''),candidates=Array.isArray(claim?.candidates)?claim.candidates as Candidate[]:[];if(!runId)return json({error:'Worker did not receive a run ID'},500);if(!candidates.length)return json({ok:true,run_id:runId,claimed:0,processed:0,concurrency});const outcomes:unknown[]=[];let fatal='';try{for(let offset=0;offset<candidates.length;offset+=concurrency){const chunk=candidates.slice(offset,offset+concurrency);const settled=await Promise.allSettled(chunk.map(async c=>{const r=await inspect(c);const {data,error}=await sb.rpc('black_pages_complete_research_candidate',{p_run_id:runId,p_candidate_id:c.id,p_result:r,p_worker:workerName});return error?{candidate_id:c.id,error:error.message}:data}));for(const item of settled)outcomes.push(item.status==='fulfilled'?item.value:{error:item.reason instanceof Error?item.reason.message:'candidate_failed'})}}catch(e){fatal=e instanceof Error?e.message:'worker_failed'}const {data:finalRun,error:finalizeError}=await sb.rpc('black_pages_finalize_research_run',{p_run_id:runId,p_error:fatal||null});if(finalizeError)return json({error:finalizeError.message,run_id:runId,outcomes},500);return json({ok:!fatal,run_id:runId,claimed:candidates.length,processed:outcomes.length,concurrency,run:finalRun,outcomes},fatal?500:200)});
