import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import * as cheerio from "npm:cheerio@1.0.0";

type Job={id:string;request_url:string};
type Item={business_name:string;city:string;state:string;postal_code:string;address:string;source_category:string;source_subcategory:string;detail_url:string;website_url:string;instagram_handle:string;public_email:string;public_phone:string;description:string;source_key:string};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json","Cache-Control":"no-store"}});
const clean=(value:string)=>String(value||'').replace(/\u200b/g,'').replace(/\s+/g,' ').trim();
const states:Record<string,string>={alabama:'AL',alaska:'AK',arizona:'AZ',arkansas:'AR',california:'CA',colorado:'CO',connecticut:'CT',delaware:'DE','district of columbia':'DC',florida:'FL',georgia:'GA',hawaii:'HI',idaho:'ID',illinois:'IL',indiana:'IN',iowa:'IA',kansas:'KS',kentucky:'KY',louisiana:'LA',maine:'ME',maryland:'MD',massachusetts:'MA',michigan:'MI',minnesota:'MN',mississippi:'MS',missouri:'MO',montana:'MT',nebraska:'NE',nevada:'NV','new hampshire':'NH','new jersey':'NJ','new mexico':'NM','new york':'NY','north carolina':'NC','north dakota':'ND',ohio:'OH',oklahoma:'OK',oregon:'OR',pennsylvania:'PA','rhode island':'RI','south carolina':'SC','south dakota':'SD',tennessee:'TN',texas:'TX',utah:'UT',vermont:'VT',virginia:'VA',washington:'WA','west virginia':'WV',wisconsin:'WI',wyoming:'WY'};
const absolute=(href:string,base:string)=>{try{return new URL(href,base).toString()}catch{return''}};
function parseAddress(raw:string){const address=clean(raw);let city='',state='',postal_code='';let m=address.match(/,\s*([^,]+),\s*([A-Z]{2})\s+(\d{5}(?:-\d{4})?)\b/i);if(m){city=clean(m[1]);state=m[2].toUpperCase();postal_code=m[3]}else{m=address.match(/,\s*([^,]+)\s*,\s*([A-Za-z ]+?)(?:\s+(\d{5}(?:-\d{4})?))?$/);if(m){city=clean(m[1]);const rawState=clean(m[2]).toLowerCase();state=states[rawState]||rawState.toUpperCase().slice(0,2);postal_code=m[3]||''}}return{address,city,state,postal_code}}
function anchorByText($:cheerio.CheerioAPI,label:string){return $('a[href]').filter((_i,a)=>clean($(a).text()).toLowerCase()===label.toLowerCase()).first()}
function phoneFromContact(text:string){const start=text.toLowerCase().indexOf('contact information');const end=text.toLowerCase().indexOf('business hours',Math.max(0,start));const chunk=start>=0?text.slice(start,end>start?end:Math.min(text.length,start+500)):'';const matches=chunk.match(/(?:\+?1[\s.-]?)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}/g)||[];for(const value of matches){const digits=value.replace(/\D/g,'');if((digits.length===10||digits.length===11)&&new Set(digits).size>=3)return clean(value)}return''}
function igHandle(href:string){try{const u=new URL(href);if(!/instagram\.com$/i.test(u.hostname.replace(/^www\./,'')))return'';return u.pathname.split('/').filter(Boolean)[0]||''}catch{return''}}
function listEntries(html:string,url:string){const $=cheerio.load(html);const seen=new Set<string>();const out:{name:string;detail_url:string}[]=[];$('h2 a[href*="/brw-campaigns/"],h3 a[href*="/brw-campaigns/"],h4 a[href*="/brw-campaigns/"]').each((_i,a)=>{const name=clean($(a).text()),detail_url=absolute($(a).attr('href')||'',url);if(!name||name.length>220||!detail_url)return;const path=new URL(detail_url).pathname;if(/^\/brw-campaigns\/?$/.test(path)||/\/brw-campaigns\/page\/\d+\/?$/.test(path)||seen.has(detail_url))return;seen.add(detail_url);out.push({name,detail_url})});return out.slice(0,20)}
async function enrich(entry:{name:string;detail_url:string}):Promise<Item>{const response=await fetch(entry.detail_url,{headers:{'User-Agent':'TheBlackPagesBRWResearch/1.0 (+public Black Restaurant Week indexing)','Accept':'text/html,application/xhtml+xml'},signal:AbortSignal.timeout(15000),redirect:'follow'});if(!response.ok)throw new Error(`detail HTTP ${response.status}`);const html=await response.text(),$=cheerio.load(html),body=clean($('body').text());const heading=$('h1,h2,h3').filter((_i,h)=>clean($(h).text()).toLowerCase()===entry.name.toLowerCase()).first();const businessName=clean(heading.text())||entry.name;const map=$('a[href*="google.com/maps"],a[href*="maps.google"]').filter((_i,a)=>/\d/.test(clean($(a).text()))).first();const parsed=parseAddress(clean(map.text()));const cuisine=(body.match(/Cuisine Type:\s*([^|]+?)(?:\||Dining Style:)/i)?.[1]||'').trim();const aboutStart=body.toLowerCase().indexOf('about');const menuStart=body.toLowerCase().indexOf('menu offerings');const description=aboutStart>=0?clean(body.slice(aboutStart+5,menuStart>aboutStart?menuStart:Math.min(body.length,aboutStart+1200))).slice(0,1000):'';const websiteAnchor=anchorByText($,'Website'),instagramAnchor=anchorByText($,'Instagram');const website_url=absolute(websiteAnchor.attr('href')||'',entry.detail_url);const instagram_handle=igHandle(absolute(instagramAnchor.attr('href')||'',entry.detail_url));return{business_name:businessName,city:parsed.city,state:parsed.state,postal_code:parsed.postal_code,address:parsed.address,source_category:'Restaurants, Food & Beverages',source_subcategory:clean(cuisine).slice(0,120),detail_url:entry.detail_url,website_url:/blackrestaurantweeks\.com|youtube\.com\/c\/BlackRestaurantWeek/i.test(website_url)?'':website_url,instagram_handle:instagram_handle.toLowerCase()==='blackrestaurantweek'?'':instagram_handle,public_email:'',public_phone:phoneFromContact(body),description,source_key:entry.detail_url.slice(0,180)}}
async function processJob(supabase:ReturnType<typeof createClient>,job:Job){try{const response=await fetch(job.request_url,{headers:{'User-Agent':'TheBlackPagesBRWResearch/1.0 (+public Black Restaurant Week indexing)','Accept':'text/html,application/xhtml+xml'},signal:AbortSignal.timeout(18000),redirect:'follow'});if(!response.ok)throw new Error(`HTTP ${response.status}`);const entries=listEntries(await response.text(),job.request_url);const settled=await Promise.allSettled(entries.map(enrich));const items=settled.filter((x):x is PromiseFulfilledResult<Item>=>x.status==='fulfilled').map(x=>x.value);const {data,error}=await supabase.rpc('black_pages_complete_external_job',{p_job_id:job.id,p_items:items,p_error:null});if(error)throw error;return{job_id:job.id,found:items.length,detail_failures:settled.length-items.length,result:data}}catch(error){const message=error instanceof Error?error.message:'brw_discovery_failed';await supabase.rpc('black_pages_complete_external_job',{p_job_id:job.id,p_items:[],p_error:message});return{job_id:job.id,error:message}}}
Deno.serve(async request=>{if(request.method!=='POST')return json({error:'Method not allowed'},405);const url=Deno.env.get('SUPABASE_URL'),key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!key)return json({error:'Worker environment incomplete'},500);const supabase=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}}),token=request.headers.get('x-worker-token')||'';const {data:authorized,error:authError}=await supabase.rpc('black_pages_authorize_worker_token',{p_token:token});if(authError||authorized!==true)return json({error:'Unauthorized'},401);let payload:{jobs?:number}={};try{payload=await request.json()}catch{payload={}}const limit=Math.min(10,Math.max(1,Number(payload.jobs)||3));const {data:claim,error:claimError}=await supabase.rpc('black_pages_claim_external_source_jobs',{p_source_key:'black_restaurant_week_national',p_limit:limit});if(claimError)return json({error:claimError.message},500);const jobs=Array.isArray(claim?.jobs)?claim.jobs as Job[]:[];if(!jobs.length)return json({ok:true,claimed:0,processed:0});const settled=await Promise.allSettled(jobs.map(job=>processJob(supabase,job)));return json({ok:true,claimed:jobs.length,processed:settled.length,outcomes:settled.map(x=>x.status==='fulfilled'?x.value:{error:String(x.reason)})})});