import { FormEvent, useEffect, useMemo, useState } from 'react'
import { ArrowRight, BadgeCheck, Building2, CheckCircle2, Globe2, Heart, MapPin, Search, Sparkles, Users, X } from 'lucide-react'
import { createClient } from '@supabase/supabase-js'

type Listing={id:string;business_name:string;category:string;city:string;state:string;short_description:string|null;website_url:string|null;instagram_handle:string|null;featured:boolean}
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
const supabase=key?createClient('https://dzlmtvodpyhetvektfuo.supabase.co',key):null
const categories=['All','Food & Beverage','Beauty & Wellness','Professional Services','Retail','Arts & Culture','Home Services','Technology']
const emptyForm={businessName:'',ownerName:'',contactEmail:'',contactPhone:'',category:'',city:'',state:'GA',websiteUrl:'',instagramHandle:'',description:'',ownershipCertification:false}

export default function App(){
 const [listings,setListings]=useState<Listing[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[apply,setApply]=useState(false),[form,setForm]=useState(emptyForm),[submitting,setSubmitting]=useState(false),[success,setSuccess]=useState(false),[formError,setFormError]=useState('')
 useEffect(()=>{let active=true;(async()=>{if(!supabase){setError('The approved directory is not configured for this release.');setLoading(false);return}const{data,error:e}=await supabase.from('black_pages_listings').select('id,business_name,category,city,state,short_description,website_url,instagram_handle,featured').eq('status','approved').order('featured',{ascending:false}).order('business_name');if(!active)return;if(e)setError('The approved directory could not be loaded.');else setListings(data??[]);setLoading(false)})();return()=>{active=false}},[])
 const shown=useMemo(()=>listings.filter(x=>(category==='All'||x.category===category)&&(!query||`${x.business_name} ${x.category} ${x.city}`.toLowerCase().includes(query.toLowerCase()))),[listings,category,query])
 async function submit(event:FormEvent){event.preventDefault();setSubmitting(true);setFormError('');try{const response=await fetch('https://dzlmtvodpyhetvektfuo.supabase.co/functions/v1/black-pages-application',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const body=await response.json();if(!response.ok)throw new Error(body.error||'Application could not be submitted.');setSuccess(true);setForm(emptyForm)}catch(e){setFormError(e instanceof Error?e.message:'Application could not be submitted.')}finally{setSubmitting(false)}}
 return <main>
  <header><a className="brand" href="#top"><span>TBP</span><strong>THE BLACK PAGES</strong></a><button onClick={()=>setApply(true)}>List your business <ArrowRight size={15}/></button></header>
  <section className="hero" id="top"><div className="shade"/><div className="hero-copy"><span className="kicker"><Sparkles size={14}/> More than a directory</span><h1>Find. Support.<br/><em>Connect. Grow.</em></h1><p>Discover approved Black-owned businesses and professionals—then put your support where it builds community.</p><div className="hero-actions"><a href="#directory">Explore the directory <ArrowRight size={17}/></a><button onClick={()=>setApply(true)}>Apply for a listing</button></div></div></section>
  <section className="pillars"><div><Search/><span><strong>Find</strong><small>Discover what you need</small></span></div><div><Heart/><span><strong>Support</strong><small>Spend with purpose</small></span></div><div><Users/><span><strong>Connect</strong><small>Build lasting relationships</small></span></div><div><Globe2/><span><strong>Grow</strong><small>Expand collective reach</small></span></div></section>
  <section className="directory" id="directory"><div className="section-head"><span>THE DIRECTORY</span><h2>Approved businesses</h2><p>Only reviewed and explicitly approved profiles appear here. Private contacts are never published.</p></div><div className="searchbar"><Search size={20}/><input aria-label="Search businesses" placeholder="Search by business, category, or city" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear search" onClick={()=>setQuery('')}><X size={17}/></button>}</div><div className="categories">{categories.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div>
  {loading?<div className="empty"><Sparkles/><h3>Opening the directory…</h3></div>:error?<div className="empty"><BadgeCheck/><h3>Directory unavailable</h3><p>{error}</p></div>:shown.length===0?<div className="empty"><Building2/><h3>{listings.length?'No matches yet':'The approved directory is opening soon'}</h3><p>{listings.length?'Try another search or category.':'Applications are open. Listings appear only after review and approval.'}</p><button onClick={()=>setApply(true)}>Apply for a listing</button></div>:<div className="grid">{shown.map(x=><article key={x.id}><span className="verified"><BadgeCheck size={14}/> Approved listing</span><h3>{x.business_name}</h3><p>{x.short_description}</p><div><span><Building2 size={13}/>{x.category}</span><span><MapPin size={13}/>{x.city}, {x.state}</span></div>{x.website_url&&<a href={x.website_url} target="_blank" rel="noreferrer">Visit business <ArrowRight size={15}/></a>}</article>)}</div>}
  </section>
  <section className="movement"><div><span>THE MOVEMENT</span><h2>Visibility creates opportunity.</h2><p>THE BLACK PAGES is building a trusted place to find, support, connect, grow, and prosper—one approved business at a time.</p><button onClick={()=>setApply(true)}>Add your business <ArrowRight size={16}/></button></div></section>
  <footer><strong>THE BLACK PAGES</strong><p>Listings are informational and do not constitute an endorsement, guarantee, or certification of services. Confirm details directly with each business.</p><small>A Kollective Hospitality Group property</small></footer>
  {apply&&<div className="modal" onMouseDown={()=>setApply(false)}><form onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><button type="button" className="close" aria-label="Close application" onClick={()=>setApply(false)}><X/></button>{success?<div className="success"><CheckCircle2/><h2>Application received.</h2><p>Your business will not appear publicly until it is reviewed and approved.</p><button type="button" onClick={()=>{setSuccess(false);setApply(false)}}>Done</button></div>:<><span className="form-kicker">LISTING APPLICATION</span><h2>Join THE BLACK PAGES.</h2><p className="form-lead">Submit accurate public business information. Approval is not automatic.</p><div className="fields"><label>Business name<input required value={form.businessName} onChange={e=>setForm({...form,businessName:e.target.value})}/></label><label>Owner/contact name<input required value={form.ownerName} onChange={e=>setForm({...form,ownerName:e.target.value})}/></label><label>Email<input required type="email" value={form.contactEmail} onChange={e=>setForm({...form,contactEmail:e.target.value})}/></label><label>Phone<input value={form.contactPhone} onChange={e=>setForm({...form,contactPhone:e.target.value})}/></label><label>Category<select required value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="">Choose</option>{categories.slice(1).map(c=><option key={c}>{c}</option>)}</select></label><label>City<input required value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>State<input required maxLength={2} value={form.state} onChange={e=>setForm({...form,state:e.target.value.toUpperCase()})}/></label><label>Website<input type="url" placeholder="https://" value={form.websiteUrl} onChange={e=>setForm({...form,websiteUrl:e.target.value})}/></label><label>Instagram<input placeholder="handle" value={form.instagramHandle} onChange={e=>setForm({...form,instagramHandle:e.target.value})}/></label><label className="wide">Business description<textarea required maxLength={1200} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="check wide"><input required type="checkbox" checked={form.ownershipCertification} onChange={e=>setForm({...form,ownershipCertification:e.target.checked})}/><span>I certify that this business is Black-owned and that I am authorized to submit it for review.</span></label></div>{formError&&<p className="form-error">{formError}</p>}<button className="submit" disabled={submitting}>{submitting?'Submitting…':'Submit for review'} <ArrowRight size={16}/></button></>}</form></div>}
 </main>
}
