-- National source expansion: prioritize structured Black Chamber directories and stage broader national directories for parser QA.
insert into public.black_pages_external_sources(source_key,source_name,adapter,base_url,ownership_signal,active,priority,notes) values
('central_florida_african_american_chamber','African American Chamber of Commerce of Central Florida','growthzone_v2','https://africanamericanchamberofcommerceofcentralflorida.growthzoneapp.com/member-directory/FindStartsWith?term=%23%21','black_chamber_directory',true,113,'African American business chamber; structured GrowthZone member directory. Human ownership review remains required.'),
('san_joaquin_black_owned_directory','African American Chamber of Commerce of San Joaquin — Black Owned Business Directory','growthzone_v2','https://business.aaccofsj.org/bobd/FindStartsWith?term=%23%21','black_chamber_directory',true,112,'Dedicated Black Owned Business Directory from the African American Chamber of Commerce of San Joaquin.'),
('nashville_black_chamber','Nashville Black Chamber of Commerce','growthzone_v2','https://nashvilleblackchamberofcommerce.growthzoneapp.com/directory/FindStartsWith?term=%23%21','black_chamber_directory',true,111,'Black Chamber business directory; structured GrowthZone source.'),
('oklahoma_city_black_chamber','Oklahoma City Black Chamber of Commerce','growthzone_v2','https://oklahomacityblackchamberofcommerce.growthzoneapp.com/memberdirectory/FindStartsWith?term=%23%21','black_chamber_directory',true,110,'Black Chamber member directory; structured GrowthZone source.'),
('blackownedcity_national','BlackOwnedCity National Directory','blackownedcity','https://blackownedcity.com/','black_business_directory',false,118,'National Black-owned business directory. Registered for dedicated parser QA before automated activation.'),
('sbba_verified_directory','Small Black Business Association Verified Directory','sbba_verified','https://sbbasupport.org/','black_business_directory',false,118,'Verified Black-owned business directory. Registered for dedicated parser QA before automated activation.'),
('the_black_book_national','The Black Book National Directory','black_book_public','https://www.black-owned-businesses.com/','black_business_directory',false,116,'National Black-owned business directory. Registered for dedicated parser QA before automated activation.'),
('infatuation_atlanta_black_restaurants','The Infatuation — Atlanta Black-Owned Restaurants Directory','curated_black_guide','https://www.theinfatuation.com/atlanta/guides/black-owned-restaurants-directory','curated_black_business_guide',false,108,'Current curated Atlanta Black-owned restaurant guide; staged for parser QA.'),
('infatuation_austin_black_restaurants','The Infatuation — Austin Black-Owned Restaurants & Food Trucks','curated_black_guide','https://www.theinfatuation.com/austin/features/austin-black-owned-restaurants-food-trucks','curated_black_business_guide',false,107,'Current curated Austin Black-owned restaurant/food-truck guide; staged for parser QA.')
on conflict(source_key) do update set source_name=excluded.source_name,adapter=excluded.adapter,base_url=excluded.base_url,ownership_signal=excluded.ownership_signal,priority=excluded.priority,notes=excluded.notes,active=excluded.active,updated_at=now();

-- Seed A-shard QA jobs for the new structured chamber sources. Weekly A-Z refresh is already handled by black_pages_internal_queue_adapter('growthzone_v2').
insert into public.black_pages_external_discovery_jobs(source_key,city,state,category_slug,page_offset,request_url,requested_count,status,attempt_count,error_message,started_at,completed_at,result_count,updated_at)
select s.source_key,null,null,null,1,regexp_replace(s.base_url,'term=.*$','term=A'),100,'pending',0,null,null,null,0,now()
from public.black_pages_external_sources s
where s.source_key in('central_florida_african_american_chamber','san_joaquin_black_owned_directory','nashville_black_chamber','oklahoma_city_black_chamber')
on conflict(source_key,request_url) do update set status='pending',attempt_count=0,error_message=null,started_at=null,completed_at=null,result_count=0,updated_at=now();
